### ISSUE TITLE
babel-preset-react requirement

### ISSUE THREAD

**Issue by kesla** [kevva/deku-media-query#1]
Hey,

We needed to add babel-preset-react to our package.json to be able to use this. Why is that a requirement? Shouldn't babel-plugin-transform-react-jsx be enough?

**Comment by kevva** [comment]
Are you using `browserify`? I think it tries to read the `package.json` of this package and use the options specified here.

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/deku-media-query/commit/b7e9e4802a561b47c626105e5d0ee8c839038153.

**Comment by kesla** [comment]
Thanks!
